services:
  ansible_controller:
    image: ansible
    build: ./master
    container_name: ansible_controller
    tty: true
    stdin_open: true
    volumes:
      - ./master:/ansible
  
  target:
    build: ./worker
    container_name: target
    expose:
      - "22"

networks:
  net:
