services:
  master:
    image: ansible
    tty: true
    stdin_open: true
    build: ./master
    container_name: master_container
  
  worker:
    build: ./worker
    container_name: worker_container

networks:
  net:
